apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-pv-camden
  namespace: camden
  labels:
    type: local
spec:
  storageClassName: document
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/db/camden"